server:
  port: 8082

spring:
  kafka:
    bootstrap-servers:
      - localhost:9094
    consumer:
      group-id: "default"
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.value.default.type: kafkaconsumer.domain.FoodOrderDto

  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password: password