server:
    port: 8080

spring:
    kafka:
      bootstrap-servers:
        - localhost:9094
      producer:
        value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
        properties:
          spring:
            json.add.type.headers: false

kafka.connection:
    topicName: t.food.order